### PR TITLE
[UI] Sessions Screen Design

### PR DESCRIPTION
**Pull request by gissilali**
# Sessions Screen Design
tweaked the SessionCard design from @Kagiri11 
Sessions Screenshot

### CODE REVIEW

**Comment by wangerekaharun** [comment]
@gissilali the screenshot is not loading

**Comment by gissilali** [comment]
> @gissilali the screenshot is not loading

It should be fixed.

**Review by wangerekaharun — APPROVED** [review]

**Comment by wangerekaharun** [comment]
@gissilali this looks good, rebase then i can merge this

**Comment by gissilali** [comment]
> @gissilali this looks good, rebase then i can merge this

Will do.

**Comment by gissilali** [comment]
> > @gissilali this looks good, rebase then i can merge this
> 
> Will do.

Done

**Review by wangerekaharun — APPROVED** [review]

**Review by misshannah — APPROVED** [review]
Looks great

**Pull request merged**
